In [14]:
import numpy as np, pandas as pd, pymysql, matplotlib, matplotlib.pyplot as plt, seaborn as sb, geopandas as gp, geopy

In [19]:
data = pd.read_csv("/mnt/docs/Progetti/BigDive/Workspace/Final_Project/Multe/VCDS-giu-lug-2017_GOOD.csv")

In [21]:
data.head()

,Anno,Articolo,Classe,Dat Infr,Loc1,Numciv1,Bisinternolettera,Loc2,Ora Infr,Sanzione accessoria,Tipoinfr,Numero Verbali,Sanzioni
0,2017,158,Autovettura,01/06/2017,GRASSI/GIUSEPPE (VIA),.,NaN,GROPELLO/GIAMBATTISTA (VIA),00:02,(Mancante),Sosta,1,1
1,2017,142,Autovettura,01/06/2017,UNITA' D'ITALIA/(CORSO),96,AFRONTE,(Altri),00:05,(Mancante),Limiti di Velocita',1,1
2,2017,142,Autovettura,01/06/2017,UNITA' D'ITALIA/(CORSO),96,AFR.EST,(Altri),00:05,(Mancante),Limiti di Velocita',1,1
3,2017,142,Autovettura,01/06/2017,UNITA' D'ITALIA/(CORSO),96,AFR.EST,(Altri),00:09,(Mancante),Limiti di Velocita',1,1
4,2017,7,Autovettura,01/06/2017,SEBASTOPOLI/(CORSO),143,FR,(Altri),00:20,(Mancante),Sosta,1,1